const {
  NEXT_PUBLIC_APP_URL,
  MP_ACCESS_TOKEN,
  API_URL,
  WHATSAPP_WEBHOOK_VERIFY_TOKEN,
  JWT_SECRET,
  WHASTAPP_FILE_MANAGER_URL,
  NEXT_PUBLIC_SUPABASE_URL,
  SERVICE_ROLE_SUPABASE_KEY,
} = process.env;

export const config = {
  NEXT_PUBLIC_APP_URL,
  MP_ACCESS_TOKEN,
  API_URL,
  WHATSAPP_WEBHOOK_VERIFY_TOKEN,
  JWT_SECRET,
  WHASTAPP_FILE_MANAGER_URL,
  NEXT_PUBLIC_SUPABASE_URL,
  SERVICE_ROLE_SUPABASE_KEY,
};
