const {
    NEXT_PUBLIC_APP_URL,
    MP_ACCESS_TOKEN,
    API_URL,
    WHATSAPP_WEBHOOK_VERIFY_TOKEN,
    JWT_SECRET,
    GOOGLE_VERTEX_LOCATION,
    GOOGLE_PROJECT_ID,
    GOOGLE_CLIENT_EMAIL,
    GOOGLE_PRIVATE_KEY,
    GOOGLE_VERTEX_PROJECT,
    CLOUD_CONVERT_API_KEY = '',
    WHASTAPP_FILE_MANAGER_URL
  } = process.env
  
  export const config = {
    NEXT_PUBLIC_APP_URL,
    MP_ACCESS_TOKEN,
    API_URL,
    WHATSAPP_WEBHOOK_VERIFY_TOKEN,
    JWT_SECRET,
    GOOGLE_VERTEX_LOCATION,
    GOOGLE_PROJECT_ID,
    GOOGLE_CLIENT_EMAIL,
    GOOGLE_PRIVATE_KEY: GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n"),
    GOOGLE_VERTEX_PROJECT,
    CLOUD_CONVERT_API_KEY,
    WHASTAPP_FILE_MANAGER_URL
  }
  